app:
  pingClient1:
    interval:
      200  # in milliseconds ping发包的时间间隔,单位毫秒
    timeout:
      5000 # in milliseconds ping如果超时会在经过这个时间后自动退出，单位毫秒
    ips:
      8.8.8.8
    urls:
      github.com
    num:
      5 # number of packets send ping每个地址发包的次数